packages:
  - playground
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@nuxt/cli@4.0.1'
  - '@nuxt/kit@4.6.1'
  - '@nuxt/nitro-server@4.6.1'
  - '@nuxt/schema@4.6.1'
  - '@nuxt/vite-builder@4.6.1'
  - '@nuxt/vite-server@4.6.1'
  - nuxt@4.6.1
verifyDepsBeforeRun: install
