name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          runtime: node@24.21.0
          cache: true

      - name: Install Playwright
        run: pnpm playwright-core install

      - run: pnpm dev:prepare
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
      - run: pnpm dev:build
